# Target: 50 MHz (Period = 20.0 ns)
create_clock -name clk -period 20.0 -waveform {0.0 10.0} [get_ports clk]
set_clock_uncertainty -setup 2.0 [get_clocks clk]
set_clock_uncertainty -hold 0.5 [get_clocks clk]
set_clock_transition 0.5 [get_clocks clk]
set_input_delay -clock clk -max 6.0 [all_inputs]
set_input_delay -clock clk -min 2.0 [all_inputs]
set_output_delay -clock clk -max 5.0 [all_outputs]
set_output_delay -clock clk -min 1.0 [all_outputs]
set_input_delay -clock clk -max 0.0 [get_ports clk]
set_input_delay -clock clk -min 0.0 [get_ports clk]
set_false_path -from [get_ports reset]
set_false_path -from [get_ports rst_n]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin Y [all_inputs]
